version: 0.0
os: linux
files:
  - source: /
    destination: /vishnu/code_deploy
hooks:
  BeforeInstall:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
