version: 0.0
os: linux
files:
  - source: /
    destination: /vishnu/code_deploy
hooks:
  BeforeInstall:
    - location: scripts/fetch_k8s_deployment.sh
      runas: root
  
  AfterInstall:
    - location: scripts/prepare_deployment.sh
      runas: root

  ApplicationStart:
    - location: scripts/deploy_k8s.sh
      runas: root

  ValidateService:
    - location: scripts/validate_deployment.sh
      runas: root



