apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2048-deployment-${VERSION}  # Dynamic deployment name
  labels:
    app: nginx-2048
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-2048
      version: ${VERSION}  # Dynamic version
  template:
    metadata:
      labels:
        app: nginx-2048
        version: ${VERSION}
    spec:
      containers:
        - name: nginx-2048
          image: 872515248362.dkr.ecr.us-east-1.amazonaws.com/2048-game-k8s
          ports:
            - containerPort: 80
