apiVersion: v1
kind: Service
metadata:
  name: nginx-2048-service
  labels:
    app: nginx-2048
spec:
  selector:
    app: nginx-2048
  ports:
    - protocol: TCP
      port: 80           # Port exposed by the service
      targetPort: 80      # Port on the container
  type: LoadBalancer     # Optional: Expose the service externally (for cloud environments)
