#!/bin/bash

# Execute the AWS CLI command and capture the output
output=$(aws deploy list-deployments \
    --application-name "2048-game-code-deployment" \
    --deployment-group-name "2048-game-code-deployment-group" \
    --query 'deployments[0]' \
    --output text)

# Convert the output to lowercase
lowercase_output=$(echo "$output" | tr '[:upper:]' '[:lower:]')

# Print the lowercase output
echo "$lowercase_output"
VERSION=$(echo "$lowercase_output" | grep -oP 'version:\s*\K\S+')

# Export the VERSION environment variable
export VERSION

# Optionally, print the version
echo "Exported VERSION: $VERSION"
